git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "2ea55be5dd88a5e8680ffb838679244b4ddd2cef"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "4f3b5a9b24bf8c70099338f0f3bda75c7f8ac09a"
