git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "dcfd018da594080af37bbddbf72c29fb9bbe418e"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "4f3b5a9b24bf8c70099338f0f3bda75c7f8ac09a"
