git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: release-v1.0.x
  commit: "e1791317e816171bff68c1f9e942cc1fef201902"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: release-v1.16.x
  commit: "f500affe3bf2e5d444a2a0f99ba68951cc18f5d2"
