git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "025110f59f2a355194002e37e458312a1d50026c"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "25271cdfacc277c5a00ce1d8500419073742cbd7"
