git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "2ea55be5dd88a5e8680ffb838679244b4ddd2cef"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "88c14bb7f8f5c05a42885c8fa51f0c794e167433"
