git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "2ea55be5dd88a5e8680ffb838679244b4ddd2cef"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: release-v1.16.x
  commit: "f500affe3bf2e5d444a2a0f99ba68951cc18f5d2"
