git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "061a198440941079054104d80a77e148430b75bb"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "f500affe3bf2e5d444a2a0f99ba68951cc18f5d2"
