git-init:
  github: tektoncd-catalog/git-clone
  path: image/git-init
  branch: main
  commit: "69d60831b69bf1621fc3359fb3717658ae0c17d4"
opc:
  github: openshift-pipelines/opc
  path: .
  branch: main
  commit: "4f3b5a9b24bf8c70099338f0f3bda75c7f8ac09a"
