name: release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false

    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - uses: goreleaser/goreleaser-action@v6.0.0
      with:
        version: latest
        args: release --timeout=60m --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
