---
apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: ecosystem-images
spec:
  displayName: "Ecosystem Images Project"
  description: |
    Tekton Ecosystem Images Project
---
apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: ecosystem-images-template
spec:
  project: ecosystem-images
  variables:
    - name: version
      description: A version number for a new development stream
    - name: branch
      description: Git repo release branch
  resources:
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Application
      metadata:
        name: "ecosystem-images-{{hyphenize .version}}"
      spec:
        displayName: "ecosystem-images-{{hyphenize .version}}"
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          appstudio.openshift.io/pac-provision: request
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
          build.appstudio.openshift.io/request: configure-pac
          image.redhat.com/generate: '{"visibility": "public"}'
        name: git-init-{{hyphenize .version}}
      spec:
        componentName: git-init-{{hyphenize .version}}
        application: ecosystem-images-{{hyphenize .version}}
        source:
          git:
            url: https://github.com/openshift-pipelines/ecosystem-images
            dockerfileUrl: git-init/Dockerfile
            revision: "{{.branch}}"
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: Component
      metadata:
        annotations:
          appstudio.openshift.io/pac-provision: request
          build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
          build.appstudio.openshift.io/request: configure-pac
          image.redhat.com/generate: '{"visibility": "public"}'
        name: opc-{{hyphenize .version}}
      spec:
        componentName: opc-{{hyphenize .version}}
        application: ecosystem-images-{{hyphenize .version}}
        source:
          git:
            url: https://github.com/openshift-pipelines/ecosystem-images
            dockerfileUrl: opc/Dockerfile
            revision: "{{.branch}}"
    - apiVersion: appstudio.redhat.com/v1beta1
      kind: IntegrationTestScenario
      metadata:
        name: ecosystem-images-enterprise-contract
      spec:
        application: ecosystem-images-{{hyphenize .version}}
        contexts:
          - description: Application testing
            name: application
        params:
          - name: POLICY_CONFIGURATION
            value: rhtap-releng-tenant/registry-standard
        resolverRef:
          params:
            - name: url
              value: "https://github.com/konflux-ci/build-definitions"
            - name: revision
              value: main
            - name: pathInRepo
              value: pipelines/enterprise-contract.yaml
          resolver: git
    - apiVersion: appstudio.redhat.com/v1alpha1
      kind: ReleasePlan
      metadata:
        labels:
          release.appstudio.openshift.io/releasePlanAdmission: ecosystem-images-prod
          release.appstudio.openshift.io/standing-attribution: "true"
        name: ecosystem-images-release-as-op
      spec:
        application: ecosystem-images-{{hyphenize .version}}
        target: rhtap-releng-tenant
        data:
          product_version: "{{.version}}"
          defaults:
            tags:
              - '{{print "{{ git_sha }}"}}'
              - '{{print "{{ git_short_sha }"`}}'
              - '{{.version}}'
              - '{{.version}}-{{ print "{{ timestamp }}"}}'
          releaseNotes:
            description: |
              Red Hat OpenShift Pipelines is a cloud-native continuous integration and
              delivery (CI/CD) solution for building pipelines using Tekton. Tekton is a
              flexible, Kubernetes-native, open-source CI/CD framework which enables
              automating deployments across multiple platforms such as Kubernetes, Serverless,
              and VMs by abstracting away the underlying details.
            references: https://docs.openshift.com/pipelines/
            solution: |
              Before applying this update, make sure all previously released errata
              relevant to your system have been applied.

              For details on how to apply this update, refer to:
              https://access.redhat.com/articles/11258
            synopsis: |
              Red Hat OpenShift Pipelines {{.version}} release
            topic: |
              Red Hat OpenShift Pipelines {{.version}} General Availability release.
