apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/ecosystem-images?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-v1.16.x" &&
      ("git-init/***".pathChanged() ||
      ".tekton/git-init-1-16-pull-request.yaml".pathChanged() ||
      ".tekton/git-init-1-16-push.yaml".pathChanged() ||
      ".tekton/image-pipeline.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ecosystem-images-1-16
    appstudio.openshift.io/component: git-init
    pipelines.appstudio.openshift.io/type: build
  name: git-init-1-16-on-push
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-16/git-init:{{revision}}
  - name: dockerfile
    value: git-init/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      {"type": "rpm", "path": "git-init"}
  pipelineRef:
    name: image-pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
